<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [DriverAutomationAssessmentV1]" duration-ms="40560" started-at="2020-05-17T18:13:00 CAT" finished-at="2020-05-17T18:13:41 CAT">
    <groups>
    </groups>
    <test name="Driver Automaton Assessment(failed)" duration-ms="40560" started-at="2020-05-17T18:13:00 CAT" finished-at="2020-05-17T18:13:41 CAT">
      <class name="com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg@6ee52dcd]" name="setup" is-config="true" duration-ms="14" started-at="2020-05-17T18:13:00 CAT" finished-at="2020-05-17T18:13:00 CAT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="ValidateUploadErrorMessage(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg@6ee52dcd]" name="ValidateUploadErrorMessage" duration-ms="37976" started-at="2020-05-17T18:13:01 CAT" data-provider="ValidateErrorMsg" finished-at="2020-05-17T18:13:39 CAT">
          <params>
            <param index="0">
              <value>
                <![CDATA[South Africa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mock Name]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[MockEmail@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Youu need to upload at least one file.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg.ValidateUploadErrorMessage(TC_ApplyOnline_ValidateUploadErrorMsg.java:182)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateUploadErrorMessage -->
      </class> <!-- com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg -->
    </test> <!-- Driver Automaton Assessment(failed) -->
  </suite> <!-- Failed suite [DriverAutomationAssessmentV1] -->
</testng-results>
