<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LT075810" ignored="0" name="Driver Automaton Assessment(failed)" tests="1" failures="1" timestamp="2020-05-17T18:13:41 CAT" time="40.56" errors="0">
  <testcase name="ValidateUploadErrorMessage" time="37.976" classname="com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg.ValidateUploadErrorMessage(TC_ApplyOnline_ValidateUploadErrorMsg.java:182)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ValidateUploadErrorMessage -->
</testsuite> <!-- Driver Automaton Assessment(failed) -->
